### ISSUE TITLE
每日播报可以生成 Markdown 么

### ISSUE THREAD

**Issue by pseudocodes** [bigwhite/gopherdaily#1]
md 对比 txt 可读性还是高一些吧 ？

**Comment by shangzongyu** [comment]
我也感觉使用 Markdown 比 TXT 好阅读多了

**Comment by bastengao** [comment]
其实用的是 markdown 的语法。欢迎小伙伴订阅 https://gopher-daily.com/ 可以通过邮件查看.

**Comment by shangzongyu** [comment]
@bastengao 主要是 Github 不渲染 .txt 结尾的文档

**Comment by bastengao** [comment]
@shangzongyu https://gopher-daily.com/issues/last 这个可能是你需要的。

**Comment by bigwhite** [comment]
@pseudocodes gopherdaily主要通过微信公众号和微博群发，这两个渠道都不支持markdown。如果这里使用纯markdown，我通过上述渠道发送时还得做转换。至于使用.md扩展名，这个没问题。后续我将.txt改为.md。

**Comment by bigwhite** [comment]
> 其实用的是 markdown 的语法。欢迎小伙伴订阅 https://gopher-daily.com/ 可以通过邮件查看.

这个mail订阅推送不错。

**Comment by bigwhite** [comment]
@bastengao 问一下你搭建的https://gopher-daily.com/  站点是自己开发的？还是基于开源工具搭建的？

**Comment by menduo** [comment]
@bastengao 证书过期了。

> 各个网站通过证书证明自己的身份，它们在设定的时间段内有效。gopher-daily.com 的证书已于 2020/5/11 过期。

**Comment by bastengao** [comment]
> @bastengao 问一下你搭建的https://gopher-daily.com/ 站点是自己开发的？还是基于开源工具搭建的？

自己用 Go 开发的。

**Comment by bastengao** [comment]
> @bastengao 证书过期了。
> 
> > 各个网站通过证书证明自己的身份，它们在设定的时间段内有效。gopher-daily.com 的证书已于 2020/5/11 过期。

证书确实有问题，已重新生效。

**Comment by bigwhite** [comment]
> > @bastengao 问一下你搭建的https://gopher-daily.com/ 站点是自己开发的？还是基于开源工具搭建的？
> 
> 自己用 Go 开发的。

手动点赞！
