### ISSUE TITLE
上周二之后就收不到订阅邮件了

### ISSUE THREAD

**Issue by verymiao** [bigwhite/gopherdaily#5]
邮箱：lkqdmsk@163.com
最后一份邮件: Gopher Daily 20211123，之前可以正常收邮件。

邮箱垃圾箱、订阅邮件、收件箱均无，已将`geren@gopher-daily.com`设置为白名单。
重新订阅显示：`已经订阅，请勿重复提交。`

**Comment by bigwhite** [comment]
gopherdaily的邮件订阅由 @bastengao https://github.com/bastengao友情提供，我刚才看了一下他的web页面 https://gopher-daily.com 是ok的，最新收录的也是20211130期。不知道有啥变故没有。待我问问吧。

**Comment by bastengao** [comment]
发信设置有问题，已经修了。

**Comment by bigwhite** [comment]
> 发信设置有问题，已经修了。

感谢👍

**Comment by verymiao** [comment]
今天已经收到订阅邮件，感谢两位 👍
