### ISSUE TITLE
关于 Gopher-daily 页面和邮件订阅均无法正常使用

### ISSUE THREAD

**Issue by lynin** [bigwhite/gopherdaily#7]
白老师你好，[gopher-daily](https://gopher-daily.com/) 貌似这几天开始就出现502错误无法打开了，邮件订阅从22年8月15日后就未再收到邮件了。希望有时间能修复下，谢谢

**Comment by Lucareful** [comment]
网站访问 502了， 希望老师有时间能修复下

**Comment by bigwhite** [comment]
have fixed
